### ISSUE TITLE
永続ボリューム追加の詳細タスク（最小限構成）

### ISSUE THREAD

**Issue by n18011** [n18011/gbc-product#3]
# 永続ボリューム追加の詳細タスク（最小限構成）

## 概要
Deployment(gbc-app)のログとDBデータ用の永続ボリュームを、kind環境での最小限構成で実装するタスクです。

### 1.1 永続化対象の詳細定義
- [ ] **ログ保存用ボリューム**
  - サイズ: 500Mi（小さめ）
  - アクセスモード: ReadWriteOnce
  - マウントパス: `/app/logs`
- [ ] **DBデータ保存用ボリューム**
  - サイズ: 1Gi（小さめ）
  - アクセスモード: ReadWriteOnce 
  - マウントパス: `/app/data`

### 1.2 kind環境での永続化方式選定
- [ ] StorageClass確認: `kubectl get storageclass`
- [ ] 最小限の実装として以下のいずれかを選択:
  - ホストパス(hostPath)ベースの永続ボリューム
  - 手動作成のPersistentVolume

### 2.1 StorageClass確認・作成（必要な場合）
- [ ] StorageClassの定義
```yaml
# local-storage.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

### 2.2 永続ボリューム(PV)の定義
- [ ] PVの定義を`base-deployment.yaml`に追加
```yaml
# base-deployment.yaml (PV部分)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gbc-app-logs-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/k8s-data/gbc-app/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gbc-app-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/k8s-data/gbc-app/db
    type: DirectoryOrCreate
```

### 2.3 永続ボリューム要求(PVC)の定義
- [ ] PVCの定義を`base-deployment.yaml`に追加
```yaml
# base-deployment.yaml (PVC部分)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gbc-app-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gbc-app-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
```

### 3.1 gbc-appのDeployment修正
- [ ] Deploymentに永続ボリューム設定を追加
```yaml
# base-deployment.yaml (Deployment部分)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbc-app
  # ...既存設定...
spec:
  # ...既存設定...
  template:
    # ...既存設定...
    spec:
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: gbc-app-logs-pvc
        - name: db-volume
          persistentVolumeClaim:
            claimName: gbc-app-db-pvc
      containers:
        - name: gbc-app
          # ...既存設定...
          volumeMounts:
            - mountPath: /app/logs
              name: logs-volume
            - mountPath: /app/data
              name: db-volume
```

### 4.1 ホストパスディレクトリの準備
- [ ] ホスト上にディレクトリを作成
```bash
# kind ノードに接続してディレクトリを作成
mkdir -p /tmp/k8s-data/gbc-app/logs
mkdir -p /tmp/k8s-data/gbc-app/db
chmod -R 777 /tmp/k8s-data  # 権限設定（開発環境用）
```

### 4.2 StorageClassとPV/PVC作成
- [ ] マニフェストの適用
```bash
kubectl apply -f local-storage.yaml
kubectl apply -f base-deployment.yaml
```

### 5.1 リソース作成確認
- [ ] 以下のコマンドで各リソースの作成を確認
```bash
kubectl get sc
kubectl get pv
kubectl get pvc
kubectl get pod
```

### 5.2 マウント確認
- [ ] Podにボリュームが正しくマウントされていることを確認
```bash
kubectl exec -it <gbc-app-pod名> -- df -h
kubectl exec -it <gbc-app-pod名> -- ls -la /app/logs /app/data
```

### 5.3 データ永続化テスト
- [ ] テスト用ファイル作成とPod再起動後の確認
```bash
# テスト用ファイル作成
kubectl exec -it <gbc-app-pod名> -- sh -c "echo 'test data' > /app/data/test.txt"
# Podを再起動
kubectl rollout restart deployment gbc-app
# 新しいPodでデータが残っているか確認
kubectl exec -it <新しいgbc-app-pod名> -- cat /app/data/test.txt
```

## 注意事項

1. kind環境では`hostPath`を使用した永続化はノードが再起動されるとデータが失われる可能性があります
2. アプリケーションが適切にマウントパスにデータを書き込む設定になっているか確認が必要です
3. 本番環境移行時には、より適切なストレージソリューションに置き換える必要があります

## 関連Issue
- #2 今後のインフラ拡張計画
