### ISSUE TITLE
ReadWriteMany対応の共有永続ストレージ実装

### ISSUE THREAD

**Issue by n18011** [n18011/gbc-product#5]
# ReadWriteMany対応の共有永続ストレージ実装

## 概要
複数ノードから同時アクセス可能な共有永続ストレージを実装し、データの一貫性を保証するとともにノード障害に対する耐性を向上させる。

## 背景と課題
現在の実装では、各ノードにローカルなhostPathタイプのボリュームを使用しているため、以下の課題があります：

1. 同じデータへの複数ノードからのアクセスができない（ReadWriteMany未対応）
2. ノード間でのデータ一貫性が保証されない
3. ノード障害時にデータが失われる可能性がある

## 1. 要件定義と設計
- **アクセスモード**: ReadWriteMany対応
- **対象データ**: 
  - ログデータ: `/app/logs`
  - DBデータ: `/app/data`
- **ストレージタイプ**:
  - Kind環境: NFS Server Provisioner
  - 本番環境: 適切な共有ストレージソリューション

### 2.1 NFS Server Provisioner導入
- [ ] Helm利用によるNFS Server Provisionerのデプロイ
  ```bash
  helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  helm install nfs-server nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=nfs-server.default.svc.cluster.local \
    --set nfs.path=/srv/nfs/kubedata \
    --set storageClass.name=nfs \
    --set storageClass.defaultClass=false
  ```

### 2.2 StorageClass定義
- [ ] NFS用のStorageClassを作成
  ```yaml
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: nfs-storage
  provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
  parameters:
    archiveOnDelete: "false"
  mountOptions:
    - vers=4.1
  ```

### 2.3 PVC定義の更新
- [ ] 共有アクセス用のPVCを再定義
  ```yaml
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: gbc-app-logs-pvc
  spec:
    accessModes:
      - ReadWriteMany  # 複数ノードからアクセス可能
    resources:
      requests:
        storage: 500Mi
    storageClassName: nfs-storage
  ---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: gbc-app-db-pvc
  spec:
    accessModes:
      - ReadWriteMany  # 複数ノードからアクセス可能
    resources:
      requests:
        storage: 1Gi
    storageClassName: nfs-storage
  ```

### 3.1 本番環境向けのストレージオプション検討
- [ ] 利用するクラウドプロバイダーに応じて最適なソリューションを選択:
  - AWS: EFS (Elastic File System)
  - GCP: Filestore
  - Azure: Azure Files
  - オンプレミス: NFS、GlusterFS、Cephなど

### 3.2 環境別設定の分離
- [ ] kustomizeを使用して環境ごとの設定を管理
  - base/: 共通設定
  - overlays/dev/: Kind環境用設定
  - overlays/production/: 本番環境用設定

### 4.1 基本機能検証
- [ ] PVC作成と正常なマウント確認
- [ ] 複数ノードのPodから同一データへのアクセス確認

### 4.2 データ一貫性検証
- [ ] 一方のPodでデータを書き込み、他方のPodでの即時可視性検証
- [ ] 同時書き込み時のファイルロック動作確認

### 4.3 耐障害性検証
- [ ] ノード障害シミュレーションと復旧後のデータ整合性確認
- [ ] Podの再スケジュール時のデータ永続性確認

## 5. 追加検討事項
- バックアップ戦略の策定
- ディザスタリカバリ計画
- パフォーマンスチューニングオプション

## 関連Issue
- #3 永続ボリューム追加の詳細タスク（最小限構成）
- #2 今後のインフラ拡張計画
